### ISSUE TITLE
Error Running I2C Example on Pi CM4

### ISSUE THREAD

**Issue by AlexKlimaj** [adafruit/Adafruit_CircuitPython_SSD1327#15] opened 2022-03-22 23:39 UTC
I have a custom Pi 4 Compute Module board with the "Adafruit Grayscale 1.5" 128x128 OLED Display" and an I2C LED driver on I2C1. I have the I2C LED driver working on the bus no problem. I am trying to get the adafruit_ssd1327 library running. When I run the example code, I get garbage displayed on the screen. I see traffic on the I2C1 bus when I run the code but the data does not look correct. It looks like a 0x80 is getting inserted every other byte.

![scope_9](https://user-images.githubusercontent.com/2019539/159593668-dfff0c0d-2f5c-4d68-ba19-999b640e26e7.png)

**Comment by AlexKlimaj** [comment] 2022-03-22 23:48
Looks like a Python3 vs 2 issue with the _INIT_SEQUENCE syntax.

**Comment by makermelissa** [comment] 2022-03-22 23:54
Are you running it with bare metal CircuitPython or on Linux? If Linux, it may be related to https://github.com/adafruit/Adafruit_Blinka_Displayio/issues/72.

**Comment by AlexKlimaj** [comment] 2022-03-22 23:58
> Are you running it with bare metal CircuitPython or on Linux? If Linux, it may be related to [adafruit/Adafruit_Blinka_Displayio#72](https://github.com/adafruit/Adafruit_Blinka_Displayio/issues/72).

Raspbian on the Pi4 Compute Module. 

Behavior matches this.
https://github.com/adafruit/Adafruit_Blinka_Displayio/issues/80

It looks like 0x80 is getting inserted between each byte in the init sequence.

**Comment by makermelissa** [comment] 2022-03-23 02:59
Closing in favor of https://github.com/adafruit/Adafruit_Blinka_Displayio/issues/80 since the issue isn't part of this library.

**Closed as completed by makermelissa** 2022-03-23 02:59 UTC
Labels: duplicate
